name: Update Gaming Calendar
on:
  schedule:
    - cron: '0 * * * *' # Runs exactly once an hour
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Fetch IGDB Data
        env:
          CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        run: |
          # 1. Get Access Token
          TOKEN=$(curl -s -X POST "https://id.twitch.tv/oauth2/token?client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=client_credentials" | jq -r '.access_token')
          
          # 2. Get Unix timestamps (Correct Ubuntu Syntax)
          START_DATE=$(date -d "30 days ago" +%s)
          END_DATE=$(date -d "+6 months" +%s)

          # 3. Query IGDB - 2 Months of past to 6 Months future
          START_DATE=$(date -d "60 days ago" +%s)
          END_DATE=$(date -d "+6 months" +%s)

          curl -X POST 'https://api.igdb.com/v4/games' \
          -H "Client-ID: $CLIENT_ID" \
          -H "Authorization: Bearer $TOKEN" \
          -d "fields 
              name, 
              summary, 
              storyline,
              hypes, 
              follows, 
              category, 
              status,
              first_release_date,
              cover.url,
              genres.name,
              game_modes.name,
              involved_companies.developer,
              involved_companies.publisher,
              involved_companies.company.name,
              screenshots.url,
              videos.video_id,
              platforms.name,
              platforms.platform_logo.url,
              # The 'websites' field handles Steam links
              websites.url, 
              websites.category,
              # The crucial 'event' data
              release_dates.date, 
              release_dates.platform.name,
              release_dates.platform.id; 

              where release_dates.date > $START_DATE 
              & release_dates.date < $END_DATE 
              & (hypes > 2 | follows > 10) 
              & cover != null 
              & status != 5; 

              sort first_release_date asc; 
              limit 500;" \
          -o games.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add games.json
          git commit -m "Update games list (Hourly Sync)" || exit 0
          git push
