name: Update Gaming Calendar
on:
  schedule:
    - cron: '0 * * * *' # Runs exactly once an hour
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Fetch IGDB Data
        env:
          CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        run: |
          # 1. Get Access Token
          TOKEN=$(curl -s -X POST "https://id.twitch.tv/oauth2/token?client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&grant_type=client_credentials" | jq -r '.access_token')
          
          # 2. Get Unix timestamps (Correct Ubuntu Syntax)
          START_DATE=$(date -d "30 days ago" +%s)
          END_DATE=$(date -d "+6 months" +%s)

          # 3. Query IGDB (Increased limit to 100 for the 6-month window)
          curl -X POST 'https://api.igdb.com/v4/release_dates' \
          -H "Client-ID: $CLIENT_ID" \
          -H "Authorization: Bearer $TOKEN" \
          -d "fields 
              game.name, 
              game.cover.url, 
              game.summary, 
              game.genres.name, 
              game.involved_companies.developer, 
              game.involved_companies.publisher, 
              game.involved_companies.company.name, 
              game.game_modes.name, 
              game.screenshots.url, 
              game.videos.video_id, 
              game.websites.url, 
              game.websites.category, 
              game.category, 
              game.status,
              game.first_release_date,
              game.platforms,
              date, 
              platform.name; 
              where date > $START_DATE & date < $END_DATE 
              & game.hypes > 5 
              & game.cover != null 
              & game.status != 5; 
              sort date asc; limit 200;" \
          -o games.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add games.json
          git commit -m "Update games list (Hourly Sync)" || exit 0
          git push
